### ISSUE TITLE
iDigBio job ran once, now fails w/ Java error

### ISSUE THREAD

**Issue by mjcollin** [gimmefreshdata/source-idigbio#3] opened 2017-05-09 21:20 UTC
Console output available here: 

http://archive.effechecka.org/job/idigbio/45/console

It looks like the other DWCA jobs are failing again too.

**Comment by jhpoelen** [comment] 2017-05-09 23:08
Was able to reproduce: root cause is that the ```update monitors``` job was running in the back ground, exhausting the maximum number of running jobs on the cluster. 

manual curl of archive import while ```update monitors``` was running resulted in:

```
   Trying 128.227.166.240... connected
> POST /v1/submissions/create HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: api.effechecka.org:7077
> Accept: */*
> Content-Type:application/json
> Content-Length: 658
> 
* upload completely sent off: 658out of 658 bytes
< HTTP/1.1 200 OK
< Date: Tue, 09 May 2017 23:03:09 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 155
< Server: Jetty(9.2.z-SNAPSHOT)
< 
{
  "action" : "CreateSubmissionResponse",
  "message" : "Already reached maximum submission size",
  "serverSparkVersion" : "2.0.1",
  "success" : false
```
for some reason, the groovy script doesn't relay stdout from curl. Instead is shows a cryptic property not defined exception.

**Comment by jhpoelen** [comment] 2017-05-09 23:16
So, system is working as expected, only the error messages are unfortunate. Tried to dig around for ways to detect the existence of a variable in jenkins groovy scripts, but alas. Perhaps @godfoder has some ideas.

**Comment by jhammock** [comment] 2017-05-10 16:05
Would it help to cancel some jobs that are currently running? And would it help to remove the older copy of gbif? That would leave us with only one copy, which is closer than I'd like to habitually cut it, but it is the lion's share of our "unnecessary" records right now, if number of records is something that could be important right now.

**Comment by jhpoelen** [comment] 2017-11-02 22:41
It seems that removing the usage of submissionResponse in error reporting removed the issue. This looks consistent with accessing response after the variable was garbage collected.

see https://github.com/gimmefreshdata/archive-importer/commit/68dc3a8c0a407cd527b6cfc00ee3943993d8b823#diff-8767fe5d74d78e6fd29d52bf09005865L131 


Closing issue for now.

**Closed as completed by jhpoelen** 2017-11-02 22:41 UTC
